[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts =
    -ra
    --cov=app
    --cov=adapters
    --cov=consumers
    --cov=domain
    --cov-report=term-missing
    --cov-report=html