from typing import Protocol

from domain.entities.flow_validator import Plan


class PlanRepository(Protocol):
    def add(self, plan: Plan) -> Plan: ...

    def get(self, plan_id: int) -> Plan | None: ...

    def list(self) -> list[Plan]: ...

    def update(self, plan: Plan) -> Plan: ...

    def delete(self, plan_id: int) -> bool: ...
