from typing import Protocol

from domain.entities.step import Step


class StepRepository(Protocol):
    def add(self, plan_id: int, step: Step) -> Step: ...

    def get(self, plan_id: int, step_id: int) -> Step | None: ...

    def list_by_plan(self, plan_id: int) -> list[Step]: ...

    def update(self, plan_id: int, step: Step) -> Step: ...

    def delete(self, plan_id: int, step_id: int) -> bool: ...

    def reorder(self, plan_id: int, positions: dict[int, int]) -> list[Step]: ...
